help:
	echo "Hello World"
lint:
	cargo check
compile:
	cargo build
run:
	cargo run
test:
	cargo test
test-coverage:
	cargo tarpaulin --out Html	
release:
	cargo run --release
debug:
	cargo with rust-gdb -- run
clear:
	cargo clear